services:
  app:
    build: .
    ports:
      - 7860:7860
    links:
      - chroma
  chroma:
    image: chromadb/chroma
    ports:
      - 8000:8000
    volumes:
      - ./src/chromadb:/chroma/chroma

