python train.py \
--overwrite_output_dir \
--num_train_epochs=2 \
--per_device_train_batch_size=32 \
--output_dir=health_encoder \
--learning_rate=3e-4 \
--warmup_ratio=0.05 \
--do_train \
--bf16 \
--optim=adamw_torch_fused \
--logging_steps=10 \
--save_strategy=epoch \
--lr_scheduler_type=cosine \
--max_grad_norm=0.3 \
--report_to=wandb \
--run_name=health_encoder \
--push_to_hub